# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add two integers using C++
#'
#' @param x First integer.
#' @param y Second integer.
#' @return The sum of x and y.
#' @export
add_cpp <- function(x, y) {
    .Call(`_Lab6_add_cpp`, x, y)
}

